#!/bin/bash
# Railway wrapper for the official couchdb image.
#
# Runs as root, before the vendor entrypoint. It renders the Railway-specific
# configuration, pins the Erlang VM to the container's CPU quota, teaches Erlang
# distribution to speak IPv6 (Railway's private network routes IPv6 between
# services), optionally bootstraps the cluster in the background, and finally
# re-enters the vendor entrypoint so its chown, admin-ini and setpriv drop still run.

set -euo pipefail

log() { echo "[railway-entrypoint] $*"; }

CONF_DIR=/opt/couchdb/etc
DATA_DIR=/opt/couchdb/data
RAILWAY_INI="$CONF_DIR/default.d/20-railway.ini"
VM_ARGS="$CONF_DIR/vm.args"
INETRC="$CONF_DIR/inetrc"

# ---------------------------------------------------------------- role & port
# coordinator : forms the cluster and creates the system databases
# member      : joins whatever the coordinator adds it to
# single      : one node, system databases created by CouchDB itself
: "${COUCHDB_CLUSTER_ROLE:=single}"
case "$COUCHDB_CLUSTER_ROLE" in
  coordinator|member|single) ;;
  *) log "FATAL: COUCHDB_CLUSTER_ROLE must be coordinator, member or single (got '$COUCHDB_CLUSTER_ROLE')"; exit 1 ;;
esac

COUCH_PORT="${PORT:-5984}"
: "${COUCHDB_CLUSTER_N:=3}"
: "${COUCHDB_CLUSTER_Q:=2}"
: "${COUCHDB_LOG_LEVEL:=warning}"
: "${COUCHDB_MAX_DOCUMENT_SIZE:=8000000}"
: "${COUCHDB_CLUSTER_PEERS:=}"
: "${COUCHDB_CORS_ORIGINS:=}"
: "${COUCHDB_CORS_HEADERS:=accept, authorization, content-type, origin, referer}"
: "${COUCHDB_CORS_METHODS:=GET, PUT, POST, HEAD, DELETE}"

if [ "$COUCHDB_CLUSTER_ROLE" = single ]; then
  COUCHDB_CLUSTER_N=1
  SINGLE_NODE=true
else
  SINGLE_NODE=false
fi

# --------------------------------------------------------------- node address
# RAILWAY_PRIVATE_DOMAIN is empty on a service's first-ever deployment, and a
# template deploys every service for the first time at once, so fall back to the
# deterministic literal rather than letting the node register a bare name.
case "${COUCHDB_NODE_HOST:-}" in
  ""|":"*) COUCHDB_NODE_HOST="${RAILWAY_PRIVATE_DOMAIN:-}" ;;
esac
if [ -z "$COUCHDB_NODE_HOST" ]; then
  COUCHDB_NODE_HOST="${RAILWAY_SERVICE_NAME:-couchdb}.railway.internal"
fi

# ------------------------------------------------------------------- cpu quota
cpu_quota() {
  local max period
  if [ -r /sys/fs/cgroup/cpu.max ]; then
    read -r max period < /sys/fs/cgroup/cpu.max || true
    if [ -n "${max:-}" ] && [ "$max" != "max" ] && [ -n "${period:-}" ] && [ "$period" -gt 0 ]; then
      echo $(( (max + period - 1) / period ))
      return
    fi
  fi
  nproc
}
QUOTA="$(cpu_quota)"
[ "$QUOTA" -ge 1 ] 2>/dev/null || QUOTA=1

# -------------------------------------------------------------------- vm.args
# The Erlang VM never reads cgroups: uncapped it sizes its scheduler pool from
# the host's core count (48 on Railway) against an 8-CPU quota.
{
  echo ""
  echo "# --- added by railway-entrypoint ---"
  echo "+S ${QUOTA}:${QUOTA}"
  echo "+SDcpu ${QUOTA}:${QUOTA}"
} >> "$VM_ARGS"
log "erlang schedulers capped to ${QUOTA} (host reports $(nproc))"

if [ "$COUCHDB_CLUSTER_ROLE" != single ]; then
  # Railway's private network routes IPv6 between services; epmd and the Erlang
  # distribution port are IPv4-only until told otherwise, and no peer ever connects.
  printf '%%%% generated by railway-entrypoint\n{inet6,true}.\n' > "$INETRC"
  chmod 0644 "$INETRC"
  {
    echo "-name couchdb@${COUCHDB_NODE_HOST}"
    echo "-proto_dist inet6_tcp"
  } >> "$VM_ARGS"
  # ERL_INETRC, not `-kernel inetrc "<path>"`: the args_file parser strips the
  # quotes, erl_parse then rejects the bare path and the VM dies at boot on
  # `Could not start kernel pid (application_controller) ({bad_environment_value,...})`.
  export ERL_INETRC="$INETRC"
  # Deliberately no ERL_EPMD_ADDRESS: epmd already listens on the IPv6 wildcard
  # unconfigured, and setting it to `::` collides with the `::1` epmd always adds
  # itself, so the bind fails and every node dies on
  # `Protocol 'inet6_tcp': register/listen error: econnrefused`.
  unset ERL_EPMD_ADDRESS || true
  log "erlang distribution: couchdb@${COUCHDB_NODE_HOST} over inet6_tcp"
fi
# The vendor entrypoint appends its own -name when NODENAME is set; ours is
# already in vm.args, so keep it out of the way.
unset NODENAME || true

# ----------------------------------------------------------------- couchdb ini
# default.d, not local.d: CouchDB writes runtime config changes into
# local.d/docker.ini, which must keep outranking this file.
{
  echo "; generated by railway-entrypoint on every boot - do not edit"
  echo ""
  echo "[chttpd]"
  # '::' is dual-stack here (the BEAM leaves ipv6_v6only at the Linux default),
  # so one socket serves both an IPv6 peer and Railway's IPv4 health prober.
  echo "bind_address = ::"
  echo "port = ${COUCH_PORT}"
  echo "require_valid_user = true"
  # ... except /_up, so the health check and the load balancer's active probe
  # have an anonymous route without opening any data surface.
  echo "require_valid_user_except_for_up = true"
  echo ""
  echo "[couchdb]"
  echo "single_node = ${SINGLE_NODE}"
  echo "max_document_size = ${COUCHDB_MAX_DOCUMENT_SIZE}"
  if [ -n "${COUCHDB_UUID:-}" ]; then
    # Every node behind the load balancer must report the same server uuid:
    # replication checkpoint ids are derived from it, so a per-node uuid silently
    # resets every client's checkpoint whenever the balancer picks another node.
    echo "uuid = ${COUCHDB_UUID}"
  fi
  echo ""
  echo "[cluster]"
  echo "q = ${COUCHDB_CLUSTER_Q}"
  echo "n = ${COUCHDB_CLUSTER_N}"
  echo ""
  echo "[log]"
  echo "writer = stderr"
  echo "level = ${COUCHDB_LOG_LEVEL}"
  if [ -n "$COUCHDB_CORS_ORIGINS" ]; then
    echo ""
    echo "[chttpd]"
    echo "enable_cors = true"
    echo ""
    echo "[cors]"
    echo "origins = ${COUCHDB_CORS_ORIGINS}"
    echo "headers = ${COUCHDB_CORS_HEADERS}"
    echo "methods = ${COUCHDB_CORS_METHODS}"
    echo "credentials = true"
  fi
} > "$RAILWAY_INI"
chmod 0644 "$RAILWAY_INI"
log "rendered ${RAILWAY_INI} (role=${COUCHDB_CLUSTER_ROLE} n=${COUCHDB_CLUSTER_N} q=${COUCHDB_CLUSTER_Q} port=${COUCH_PORT})"

mkdir -p "$DATA_DIR"

# ------------------------------------------------------------------ bootstrap
# Behind the exec, never in front of it: in front it burns the health-check
# window waiting for peers that cannot start until this service is healthy.
bootstrap_cluster() {
  set +e
  local base="http://127.0.0.1:${COUCH_PORT}"
  local auth="${COUCHDB_USER}:${COUCHDB_PASSWORD}"
  local expected=1 peer i code n

  for i in $(seq 1 150); do
    curl -fsS --max-time 5 "$base/_up" >/dev/null 2>&1 && break
    sleep 2
  done
  log "local node is up, joining peers"

  for peer in $COUCHDB_CLUSTER_PEERS; do
    expected=$(( expected + 1 ))
    for i in $(seq 1 225); do
      curl -fsS --max-time 5 "http://${peer}:${COUCH_PORT}/_up" >/dev/null 2>&1 && break
      sleep 4
    done
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 -u "$auth" \
      -X PUT "$base/_node/_local/_nodes/couchdb@${peer}" \
      -H 'Content-Type: application/json' -d '{}')
    # 201 created, 409 already a member
    log "join couchdb@${peer} -> HTTP ${code}"
  done

  # cluster_nodes is the _nodes database, which is what shard placement reads, so
  # the system databases must not be created until it is complete.
  for i in $(seq 1 60); do
    n=$(curl -fsS --max-time 10 -u "$auth" "$base/_membership" 2>/dev/null | jq -r '.cluster_nodes | length' 2>/dev/null)
    case "${n:-}" in ''|*[!0-9]*) n=0 ;; esac
    [ "$n" -ge "$expected" ] && break
    sleep 5
  done
  log "cluster membership: ${n:-0}/${expected} nodes registered"

  # System databases are created only once every node is a member, or they land
  # with n=1 on this node alone and stay that way forever.
  for db in _users _replicator _global_changes; do
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 -u "$auth" -X PUT "$base/$db")
    log "system database ${db} -> HTTP ${code}"
  done

  # all_nodes is `[node()|nodes()]`, i.e. the peers Erlang distribution has actually
  # connected to. cluster_nodes can be complete while this is 1, which is a cluster
  # that places shards correctly and reaches quorum on none of them.
  for i in $(seq 1 60); do
    n=$(curl -fsS --max-time 10 -u "$auth" "$base/_membership" 2>/dev/null | jq -r '.all_nodes | length' 2>/dev/null)
    case "${n:-}" in ''|*[!0-9]*) n=0 ;; esac
    [ "$n" -ge "$expected" ] && break
    sleep 5
  done
  if [ "${n:-0}" -ge "$expected" ]; then
    log "cluster bootstrap finished: ${n}/${expected} nodes connected over erlang distribution"
  else
    log "WARNING: only ${n:-0}/${expected} nodes connected over erlang distribution; writes will not reach quorum"
  fi
}

if [ "$COUCHDB_CLUSTER_ROLE" = coordinator ]; then
  if [ -z "${COUCHDB_USER:-}" ] || [ -z "${COUCHDB_PASSWORD:-}" ]; then
    log "FATAL: the coordinator needs COUCHDB_USER and COUCHDB_PASSWORD to bootstrap the cluster"
    exit 1
  fi
  bootstrap_cluster &
fi

# Re-enter the vendor entrypoint so it still chowns /opt/couchdb, writes the
# [admins] block and the erlang cookie, and drops to uid 5984 via setpriv.
log "handing off to the couchdb entrypoint"
exec /docker-entrypoint.sh /opt/couchdb/bin/couchdb
